# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27c0e0bfd8c71cbdf738f47d1b50d2b123ce3a200f99821a62759a0b7091783757e84780d9b52da03b4449e890397098e7e192e5f5148b65450b3a751478c6ad

test:
  secret_key_base: 2d580dc432344d3b25ffca4ba6301fcc2b65df2c89a37fdbe594e35fc5364572e8e5e81b0a49eb0e164d7a61a55623985f4aaed0da076119b7df1e8972f60762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
